### ISSUE TITLE
Feature request: CLT nesting

### ISSUE THREAD

**Issue by aldbernier** [cwapi3d/cwapi3dcpp#1]
Hi,
 
I'm currently working on CLT panel nesting and it would be nice to have these features implemented:
 
- Get the list of the optimization groups.
- Get the list of the panels in a specific optimization group.
- Get the list of the elements in a specific panel.
- Get the position and orientation of an element in a panel.
- Create a panel in an optimization group.
- Set the position of an element in a panel.
 
Thanks!

**Comment by jspaquet** [comment]
Hi,

I know of one client who achieved this using the external nesting (BTL) feature of the 3D (which is built specifically for this use-case). Considering that this workaround exists and works, and the available development time of our team, we are unable to implement such a feature for the foreseeable future. The request has been filed on our side so if we ever decide to implement it we will update you at that time. 

Thanks,
